#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HappyTravel.Resource", IsApplication=true)]

namespace HappyTravel
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int slide_right = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int slide_up = 2131034113;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0a0000
			public const int abc_action_bar_embed_tabs = 2131361792;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070003
			public const int notification_action_color_filter = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int notification_icon_bg_color = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int notification_material_background_media_default_color = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int primary_text_default_material_dark = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int ripple_material_light = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int secondary_text_default_material_dark = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int secondary_text_default_material_light = 2131165190;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0b0004
			public const int compat_button_inset_horizontal_material = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int compat_button_inset_vertical_material = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int compat_button_padding_horizontal_material = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int compat_button_padding_vertical_material = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int compat_control_corner_material = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int notification_action_icon_size = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int notification_action_text_size = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int notification_big_circle_margin = 2131427339;
			
			// aapt resource value: 0x7f0b0001
			public const int notification_content_margin_start = 2131427329;
			
			// aapt resource value: 0x7f0b000c
			public const int notification_large_icon_height = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int notification_large_icon_width = 2131427341;
			
			// aapt resource value: 0x7f0b0002
			public const int notification_main_column_padding_top = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int notification_media_narrow_margin = 2131427331;
			
			// aapt resource value: 0x7f0b000e
			public const int notification_right_icon_size = 2131427342;
			
			// aapt resource value: 0x7f0b0000
			public const int notification_right_side_padding_top = 2131427328;
			
			// aapt resource value: 0x7f0b000f
			public const int notification_small_icon_background_padding = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int notification_small_icon_size_as_large = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int notification_subtext_size = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public const int notification_top_pad = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public const int notification_top_pad_large_text = 2131427347;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int home = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_action_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_low = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_low_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_bg_low_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notification_bg_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notification_bg_normal_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_icon_background = 2130837515;
			
			// aapt resource value: 0x7f02000f
			public const int notification_template_icon_bg = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int notification_template_icon_low_bg = 2130837520;
			
			// aapt resource value: 0x7f02000c
			public const int notification_tile_bg = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int notify_panel_notification_icon_bg = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ProgressBarStyle = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0036
			public const int action0 = 2131492918;
			
			// aapt resource value: 0x7f0c0033
			public const int action_container = 2131492915;
			
			// aapt resource value: 0x7f0c003a
			public const int action_divider = 2131492922;
			
			// aapt resource value: 0x7f0c0034
			public const int action_image = 2131492916;
			
			// aapt resource value: 0x7f0c0035
			public const int action_text = 2131492917;
			
			// aapt resource value: 0x7f0c0044
			public const int actions = 2131492932;
			
			// aapt resource value: 0x7f0c0025
			public const int articleListView = 2131492901;
			
			// aapt resource value: 0x7f0c0005
			public const int async = 2131492869;
			
			// aapt resource value: 0x7f0c0006
			public const int blocking = 2131492870;
			
			// aapt resource value: 0x7f0c0014
			public const int btnAddComment = 2131492884;
			
			// aapt resource value: 0x7f0c001d
			public const int btnDialogSignIn = 2131492893;
			
			// aapt resource value: 0x7f0c0021
			public const int btnDialogSignUp = 2131492897;
			
			// aapt resource value: 0x7f0c002c
			public const int btnHome = 2131492908;
			
			// aapt resource value: 0x7f0c0030
			public const int btnLogout = 2131492912;
			
			// aapt resource value: 0x7f0c002b
			public const int btnMe = 2131492907;
			
			// aapt resource value: 0x7f0c002d
			public const int btnPost = 2131492909;
			
			// aapt resource value: 0x7f0c004b
			public const int btnPublish = 2131492939;
			
			// aapt resource value: 0x7f0c0028
			public const int btnSignIn = 2131492904;
			
			// aapt resource value: 0x7f0c002a
			public const int btnSignUp = 2131492906;
			
			// aapt resource value: 0x7f0c0037
			public const int cancel_action = 2131492919;
			
			// aapt resource value: 0x7f0c003f
			public const int chronometer = 2131492927;
			
			// aapt resource value: 0x7f0c0011
			public const int commentLayout = 2131492881;
			
			// aapt resource value: 0x7f0c0012
			public const int commentTextView = 2131492882;
			
			// aapt resource value: 0x7f0c0015
			public const int commentsListView = 2131492885;
			
			// aapt resource value: 0x7f0c000a
			public const int detailScrollView = 2131492874;
			
			// aapt resource value: 0x7f0c0046
			public const int end_padder = 2131492934;
			
			// aapt resource value: 0x7f0c0007
			public const int forever = 2131492871;
			
			// aapt resource value: 0x7f0c0022
			public const int homeBannerImageView = 2131492898;
			
			// aapt resource value: 0x7f0c0023
			public const int homeRL = 2131492899;
			
			// aapt resource value: 0x7f0c0041
			public const int icon = 2131492929;
			
			// aapt resource value: 0x7f0c0045
			public const int icon_group = 2131492933;
			
			// aapt resource value: 0x7f0c0026
			public const int imageView1 = 2131492902;
			
			// aapt resource value: 0x7f0c0040
			public const int info = 2131492928;
			
			// aapt resource value: 0x7f0c0008
			public const int italic = 2131492872;
			
			// aapt resource value: 0x7f0c0000
			public const int line1 = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int line3 = 2131492865;
			
			// aapt resource value: 0x7f0c000d
			public const int linearLayout1 = 2131492877;
			
			// aapt resource value: 0x7f0c0024
			public const int listViewRL = 2131492900;
			
			// aapt resource value: 0x7f0c0039
			public const int media_actions = 2131492921;
			
			// aapt resource value: 0x7f0c0032
			public const int myPostListView = 2131492914;
			
			// aapt resource value: 0x7f0c0009
			public const int normal = 2131492873;
			
			// aapt resource value: 0x7f0c0043
			public const int notification_background = 2131492931;
			
			// aapt resource value: 0x7f0c003c
			public const int notification_main_column = 2131492924;
			
			// aapt resource value: 0x7f0c003b
			public const int notification_main_column_container = 2131492923;
			
			// aapt resource value: 0x7f0c000b
			public const int relativeLayout1 = 2131492875;
			
			// aapt resource value: 0x7f0c0042
			public const int right_icon = 2131492930;
			
			// aapt resource value: 0x7f0c003d
			public const int right_side = 2131492925;
			
			// aapt resource value: 0x7f0c0047
			public const int scrollView1 = 2131492935;
			
			// aapt resource value: 0x7f0c0038
			public const int status_bar_latest_event_content = 2131492920;
			
			// aapt resource value: 0x7f0c0002
			public const int text = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int text2 = 2131492867;
			
			// aapt resource value: 0x7f0c002e
			public const int textView1 = 2131492910;
			
			// aapt resource value: 0x7f0c000e
			public const int textView2 = 2131492878;
			
			// aapt resource value: 0x7f0c0049
			public const int textView3 = 2131492937;
			
			// aapt resource value: 0x7f0c003e
			public const int time = 2131492926;
			
			// aapt resource value: 0x7f0c0004
			public const int title = 2131492868;
			
			// aapt resource value: 0x7f0c0017
			public const int txtAuthor = 2131492887;
			
			// aapt resource value: 0x7f0c001a
			public const int txtByUser = 2131492890;
			
			// aapt resource value: 0x7f0c0013
			public const int txtComment = 2131492883;
			
			// aapt resource value: 0x7f0c0019
			public const int txtCommentItem = 2131492889;
			
			// aapt resource value: 0x7f0c004a
			public const int txtContent = 2131492938;
			
			// aapt resource value: 0x7f0c0027
			public const int txtCreatAccount = 2131492903;
			
			// aapt resource value: 0x7f0c000f
			public const int txtDetailAuthor = 2131492879;
			
			// aapt resource value: 0x7f0c0010
			public const int txtDetailContent = 2131492880;
			
			// aapt resource value: 0x7f0c000c
			public const int txtDetailTitle = 2131492876;
			
			// aapt resource value: 0x7f0c0018
			public const int txtItemAuthor = 2131492888;
			
			// aapt resource value: 0x7f0c0016
			public const int txtItemTitle = 2131492886;
			
			// aapt resource value: 0x7f0c002f
			public const int txtMeUsername = 2131492911;
			
			// aapt resource value: 0x7f0c0031
			public const int txtMyPosts = 2131492913;
			
			// aapt resource value: 0x7f0c0029
			public const int txtOr = 2131492905;
			
			// aapt resource value: 0x7f0c001c
			public const int txtPassword = 2131492892;
			
			// aapt resource value: 0x7f0c001f
			public const int txtPassword1 = 2131492895;
			
			// aapt resource value: 0x7f0c0020
			public const int txtPassword2 = 2131492896;
			
			// aapt resource value: 0x7f0c0048
			public const int txtTitle = 2131492936;
			
			// aapt resource value: 0x7f0c001b
			public const int txtUsername = 2131492891;
			
			// aapt resource value: 0x7f0c001e
			public const int txtUsernameSignUp = 2131492894;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int cancel_button_image_alpha = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int status_bar_notification_info_maxnum = 2131230721;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int ArticleDetail = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ArticleItemLayout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int CommentItemLayout = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Dialog_Sign_In = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Dialog_Sign_Up = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Home = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Main = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int MenuButton = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int MyProfile = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int notification_action = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int notification_action_tombstone = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int notification_media_action = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int notification_media_cancel_action = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int notification_template_big_media = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int notification_template_big_media_custom = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int notification_template_big_media_narrow = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int notification_template_big_media_narrow_custom = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int notification_template_custom_big = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int notification_template_icon_group = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int notification_template_lines_media = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int notification_template_media = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int notification_template_media_custom = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int notification_template_part_chronometer = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int notification_template_part_time = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int Post = 2130968600;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int banner = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int banner1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int banner2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int banner3 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int banner4 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int home = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int home3 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Icon = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Ion = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int logo = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int me = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int pen = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int pen1 = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int person1 = 2130903053;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090002
			public const int app_name = 2131296258;
			
			// aapt resource value: 0x7f09000a
			public const int author_hint = 2131296266;
			
			// aapt resource value: 0x7f09000e
			public const int btnComment_hint = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int by_user = 2131296271;
			
			// aapt resource value: 0x7f090009
			public const int comment_hint = 2131296265;
			
			// aapt resource value: 0x7f09000d
			public const int content_hint = 2131296269;
			
			// aapt resource value: 0x7f090007
			public const int error_hint = 2131296263;
			
			// aapt resource value: 0x7f090003
			public const int first_name_hint = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int hello = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int logout_hint = 2131296268;
			
			// aapt resource value: 0x7f090005
			public const int password_again_hint = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int password_hint = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int status_bar_notification_info_overflow = 2131296256;
			
			// aapt resource value: 0x7f090008
			public const int title_hint = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int username_hint = 2131296262;
			
			// aapt resource value: 0x7f09000b
			public const int welcome_hint = 2131296267;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060005
			public const int TextAppearance_Compat_Notification = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int TextAppearance_Compat_Notification_Info = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int TextAppearance_Compat_Notification_Media = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int TextAppearance_Compat_Notification_Time = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int TextAppearance_Compat_Notification_Title = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int Widget_Compat_NotificationActionContainer = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int Widget_Compat_NotificationActionText = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int dialog_animation = 2131099660;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
